// const auth = require('./auth')
const user = require('./user')
const bookmark = require('./bookmark')
// const sign = require('./sign')
// const reward = require('./reward')
// const cms = require('./cms')
// const stock = require('./stock')
// const qs = require('./qs')
const article = require('./article')
const tag = require('./tag')
const share = require('./share')
const tip = require('./tip')

module.exports = app => app.use(article, bookmark, tag, share, tip, user)
